FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ /app/

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
